
console.log(audioBuffer)
<Buffer 49 44 33 04 00 00 00 00 0 .... >


<ref *2> VoiceChannel {
  type: 2,
  guild: <ref *1> Guild {
    id: '511898131038732304',
    name: 'BR',
    icon: 'a_06caf010b6bd845bb4eca719c81d333a',
    features: [
      'GUESTS_ENABLED',
      'ANIMATED_ICON',
      'SOUNDBOARD',
      'THREE_DAY_THREAD_ARCHIVE',
      'CHANNEL_ICON_EMOJIS_GENERATED',
      'INVITE_SPLASH'
    ],
    commands: GuildApplicationCommandManager {
      permissions: [ApplicationCommandPermissionsManager],
      guild: [Circular *1]
    },
    members: GuildMemberManager { guild: [Circular *1] },
    channels: GuildChannelManager { guild: [Circular *1] },
    bans: GuildBanManager { guild: [Circular *1] },
    roles: RoleManager { guild: [Circular *1] },
    presences: PresenceManager {},
    voiceStates: VoiceStateManager { guild: [Circular *1] },
    stageInstances: StageInstanceManager { guild: [Circular *1] },
    invites: GuildInviteManager { guild: [Circular *1] },
    scheduledEvents: GuildScheduledEventManager { guild: [Circular *1] },
    autoModerationRules: AutoModerationRuleManager { guild: [Circular *1] },
    available: true,
    shardId: 0,
    splash: null,
    banner: null,
    description: null,
    verificationLevel: 0,
    vanityURLCode: null,
    nsfwLevel: 0,
    premiumSubscriptionCount: 2,
    discoverySplash: null,
    memberCount: 17,
    large: false,
    premiumProgressBarEnabled: false,
    applicationId: null,
    afkTimeout: 3600,
    afkChannelId: null,
    systemChannelId: '511898131563282433',
    premiumTier: 1,
    widgetEnabled: null,
    widgetChannelId: null,
    explicitContentFilter: 0,
    mfaLevel: 0,
    joinedTimestamp: 1719118028513,
    defaultMessageNotifications: 0,
    systemChannelFlags: SystemChannelFlagsBitField { bitfield: 0 },
    maximumMembers: 500000,
    maximumPresences: null,
    maxVideoChannelUsers: 25,
    maxStageVideoChannelUsers: 50,
    approximateMemberCount: null,
    approximatePresenceCount: null,
    vanityURLUses: null,
    rulesChannelId: null,
    publicUpdatesChannelId: null,
    preferredLocale: 'en-US',
    safetyAlertsChannelId: null,
    ownerId: '378543198953406464',
    emojis: GuildEmojiManager { guild: [Circular *1] },
    stickers: GuildStickerManager { guild: [Circular *1] }
  },
  guildId: '511898131038732304',
  permissionOverwrites: PermissionOverwriteManager { channel: [Circular *2] },
  messages: GuildMessageManager { channel: [Circular *2] },
  nsfw: false,
  flags: ChannelFlagsBitField { bitfield: 0 },
  id: '1254309842877939732',
  name: '봇 테스트',
  rawPosition: 4,
  parentId: '511898131563282434',
  rtcRegion: null,
  bitrate: 64000,
  userLimit: 0,
  videoQualityMode: null,
  lastMessageId: null,
  rateLimitPerUser: 0
}


